CREATE DATABASE BIBLIOTEC;
USE BIBLIOTEC;

CREATE TABLE LIVRO(
	ID INT NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    DATA_PUBLICACAO DATE NOT NULL,
    AUTOR VARCHAR(50) NOT NULL,
    DISPONIBILIDADE BOOLEAN NOT NULL,
    ULTIMA_RETIRADA DATE,
PRIMARY KEY (ID)
);

CREATE TABLE ALUNO(
	ID INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CPF CHAR(11) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE ATENDENTE(
	ID INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE BIBLIOTECA(
	DATA_DEVOLUCAO DATE NOT NULL,
    DATA_RETIRADA DATE NOT NULL,
	ID_LIVRO INT NOT NULL,
    ID_ALUNO INT NOT NULL,
    ID_ATENDENTE INT NOT NULL,

FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO(ID),
FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID),
FOREIGN KEY (ID_ATENDENTE) REFERENCES ATENDENTE(ID)
);



 
  