USE REDE_SOCIAL;

SELECT * FROM POSTAGEM WHERE ID_USUARIO NOT IN(1);
SELECT * FROM POSTAGEM WHERE ID_USUARIO NOT IN(2);
SELECT * FROM POSTAGEM WHERE ID_USUARIO NOT IN(3);
SELECT * FROM POSTAGEM WHERE ID_USUARIO NOT IN(4);

SELECT 
	 USUARIO.NOME, COMENTARIO.DESCRICAO_MENSAGEM
FROM 
	COMENTARIO, USUARIO, POSTAGEM
WHERE
	POSTAGEM.ID = COMENTARIO.ID_POSTAGEM
	AND
	COMENTARIO.ID_USUARIO = USUARIO.ID
    AND
    COMENTARIO.ID_POSTAGEM = 1;
    
SELECT 
	 USUARIO.NOME, COMENTARIO.DESCRICAO_MENSAGEM
FROM 
	COMENTARIO, USUARIO, POSTAGEM
WHERE
	POSTAGEM.ID = COMENTARIO.ID_POSTAGEM
	AND
	COMENTARIO.ID_USUARIO = USUARIO.ID
    AND
    COMENTARIO.ID_POSTAGEM = 2;
    
SELECT 
	 USUARIO.NOME, COMENTARIO.DESCRICAO_MENSAGEM
FROM 
	COMENTARIO, USUARIO, POSTAGEM
WHERE
	POSTAGEM.ID = COMENTARIO.ID_POSTAGEM
	AND
	COMENTARIO.ID_USUARIO = USUARIO.ID
    AND
    COMENTARIO.ID_POSTAGEM = 3;
    
SELECT 
	 USUARIO.NOME, COMENTARIO.DESCRICAO_MENSAGEM
FROM 
	COMENTARIO, USUARIO, POSTAGEM
WHERE
	POSTAGEM.ID = COMENTARIO.ID_POSTAGEM
	AND
	COMENTARIO.ID_USUARIO = USUARIO.ID
    AND
    COMENTARIO.ID_POSTAGEM = 4;
    
SELECT 
	REACAO.DESCRICAO_REACAO, USUARIO.NOME
FROM
	REACAO, USUARIO, POSTAGEM, POSTAGEM_USUARIO_REACAO
WHERE 
	POSTAGEM_USUARIO_REACAO.ID_POSTAGEM = POSTAGEM.ID
    AND
    POSTAGEM_USUARIO_REACAO.ID_USUARIO = USUARIO.ID
    AND
    POSTAGEM_USUARIO_REACAO.ID_REACAO = REACAO.ID
    AND
    POSTAGEM.ID = 2
    AND
    REACAO.ID = 1;